# Create a user
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "Tester",
    "email": "tester@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "user"
}

###
GET http://localhost:4000/users

###
GET http://localhost:4000/users/

###
PATCH http://localhost:4000/users/16535f20-3e90-4e5a-b76c-ba78476d5bd8

###
DELETE hhtp://localhost"4000/users/16535f20-3e90-4e5a-b76c-ba78476d5bd8

### 
// Login User
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "123456" 
}

### 
// Login User
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "tester@gmail.com",
    "password": "123456" 
}

###
GET http://localhost:4000/me

###
DELETE http://localhost:4000/logOut

###
GET http://localhost:4000/products

### 
POST http://localhost:4000/products
Content-Type: application/json

{
    "name": "Iphone 12",
    "price": 997
}


###
PATCH http://localhost:4000/products/cfe12e80-7919-4481-a12b-37444c34a126
Content-Type: application/json

{
    "name": "Iphone 13 PM",
    "price": 1298
}

###
POST http://localhost:4000/products
Content-Type: application/json

{
    "name": "Iphone 12",
    "price": 897
}

###
POST http://localhost:4000/products
Content-Type: application/json

{
    "name": "Iphone 10",
    "price": 797
}


###
DELETE http://localhost:4000/products/cfe12e80-7919-4481-a12b-37444c34a126